steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/my-gcp-pca-1/hello-gcp-repo/hello-gcp:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west3-docker.pkg.dev/my-gcp-pca-1/hello-gcp-repo/hello-gcp:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hello-gcp'
      - '--image=europe-west3-docker.pkg.dev/my-gcp-pca-1/hello-gcp-repo/hello-gcp:$COMMIT_SHA'
      - '--region=europe-west3'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'europe-west3-docker.pkg.dev/my-gcp-pca-1/hello-gcp-repo/hello-gcp:$COMMIT_SHA'